var annotated_dup =
[
    [ "CodigoProjeto", "class_codigo_projeto.html", "class_codigo_projeto" ],
    [ "Custo", "class_custo.html", "class_custo" ],
    [ "Data", "class_data.html", "class_data" ],
    [ "Email", "class_email.html", "class_email" ],
    [ "EstadoProjeto", "class_estado_projeto.html", "class_estado_projeto" ],
    [ "FaseProjeto", "class_fase_projeto.html", "class_fase_projeto" ],
    [ "Funcao", "class_funcao.html", "class_funcao" ],
    [ "Matricula", "class_matricula.html", "class_matricula" ],
    [ "Nome", "class_nome.html", "class_nome" ],
    [ "Senha", "class_senha.html", "class_senha" ],
    [ "Telefone", "class_telefone.html", "class_telefone" ],
    [ "TesteCodigoProjeto", "class_teste_codigo_projeto.html", "class_teste_codigo_projeto" ],
    [ "TesteCusto", "class_teste_custo.html", "class_teste_custo" ],
    [ "TesteData", "class_teste_data.html", "class_teste_data" ],
    [ "TesteEmail", "class_teste_email.html", "class_teste_email" ],
    [ "TesteEstadoProjeto", "class_teste_estado_projeto.html", "class_teste_estado_projeto" ],
    [ "TesteFaseProjeto", "class_teste_fase_projeto.html", "class_teste_fase_projeto" ],
    [ "TesteFuncao", "class_teste_funcao.html", "class_teste_funcao" ],
    [ "TesteMatricula", "class_teste_matricula.html", "class_teste_matricula" ],
    [ "TesteNome", "class_teste_nome.html", "class_teste_nome" ],
    [ "TesteSenha", "class_teste_senha.html", "class_teste_senha" ],
    [ "TesteTelefone", "class_teste_telefone.html", "class_teste_telefone" ]
];